workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Pet API:
        inputs:
            - location: ../openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/ritza-rzx/ritza/pet-api
targets:
    sdk:
        target: typescript
        source: Pet API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/ritza-rzx/ritza/pet-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
