/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { petsCreate } from "../funcs/petsCreate.js";
import { petsFindOneCat } from "../funcs/petsFindOneCat.js";
import { petsFindOneDog } from "../funcs/petsFindOneDog.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Pets extends ClientSDK {
  /**
   * Create pet
   */
  async create(
    request: operations.CreateRequestBody,
    options?: RequestOptions,
  ): Promise<operations.CreateResponse> {
    return unwrapAsync(petsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get cat
   */
  async findOneCat(
    request: operations.FindOneCatRequest,
    options?: RequestOptions,
  ): Promise<components.Cat> {
    return unwrapAsync(petsFindOneCat(
      this,
      request,
      options,
    ));
  }

  /**
   * Get dog
   */
  async findOneDog(
    request: operations.FindOneDogRequest,
    options?: RequestOptions,
  ): Promise<components.Dog> {
    return unwrapAsync(petsFindOneDog(
      this,
      request,
      options,
    ));
  }
}
